const Anthropic = require('@anthropic-ai/sdk');

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const MEDICAL_SYSTEM_PROMPT = `You are a medical data extraction assistant for ClinicalCoPilot.

Your task is to analyze blood work report text and extract all lab values and identify chronic disease risk indicators.

CRITICAL RULES:
1. Return ONLY valid JSON — no preamble, no markdown, no explanation outside the JSON
2. Never invent lab values that are not clearly present in the text
3. Use standard adult clinical reference ranges unless age/gender context is provided
4. Risk levels must be exactly one of: "normal", "borderline", or "high"
5. AI confidence must be exactly one of: "high", "medium", or "low"

RESPONSE FORMAT (strict JSON):
{
  "lab_values": [
    {
      "biomarker_name": "HbA1c",
      "value": 6.2,
      "unit": "%",
      "reference_min": 4.0,
      "reference_max": 5.6,
      "status": "borderline"
    }
  ],
  "risk_flags": [
    {
      "disease_category": "Type 2 Diabetes",
      "risk_level": "borderline",
      "explanation": "HbA1c of 6.2% is in the pre-diabetic range (5.7-6.4%). This warrants monitoring and lifestyle changes. Consult your physician.",
      "ai_confidence": "high",
      "contributing_biomarkers": ["HbA1c"]
    }
  ],
  "extraction_notes": "Note any values that were unclear or could not be extracted",
  "disclaimer": "This analysis is generated by AI and is not a medical diagnosis. Always consult a qualified physician before making any health decisions."
}

CHRONIC DISEASE CATEGORIES TO CHECK:
- Type 2 Diabetes: HbA1c, Fasting Glucose, Insulin
- Chronic Kidney Disease (CKD): Creatinine, eGFR, BUN, Uric Acid
- Liver Disease: ALT, AST, GGT, Bilirubin, Albumin
- Thyroid Disorders: TSH, Free T3, Free T4
- Cardiovascular Risk: LDL, HDL, Triglycerides, Total Cholesterol, hsCRP
- Vitamin Deficiencies: Vitamin D, B12, Folate, Iron, Zinc
- Anemia: Hemoglobin, Hematocrit, RBC, Ferritin, B12

Only include a risk_flag entry if there is actual evidence in the blood work. Do not flag diseases where no relevant biomarkers are present in the report.`;

const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 2000;

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function analyzeBloodWork(extractedText) {
  let lastError;

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const response = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 2000,
        system: MEDICAL_SYSTEM_PROMPT,
        messages: [
          {
            role: 'user',
            content: `Analyze this blood work report:\n\n${extractedText}`,
          },
        ],
      });

      const content = response.content[0]?.text;
      if (!content) {
        throw new Error('Empty response from Claude API');
      }

      return content;
    } catch (err) {
      lastError = err;
      console.error(`Claude API attempt ${attempt} failed:`, err.message);

      if (attempt < MAX_RETRIES) {
        await sleep(RETRY_DELAY_MS);
      }
    }
  }

  throw new Error(`Claude API failed after ${MAX_RETRIES} attempts: ${lastError.message}`);
}

module.exports = { analyzeBloodWork, MEDICAL_SYSTEM_PROMPT };
